### ISSUE TITLE
Application close when context menu closes

### ISSUE THREAD

**Issue by arteven** [BrainCrumbz/caliburn-micro-wpf-notifyicon-poc#1]
Hi,

When I try open context menu - application close. Any solutions for this?
Project: 01-SysTrayNoWindow

**Comment by BrainCrumbz** [comment]
Hi there. 

If you're looking for a **complete** proof of concept, please have a look at *04-SysTrayWithinWindow*. The other solutions, from 1 to 3, show somehow the process of learning, that is, how we got from the initial try to the final working solution.

For a more complete description, try with main [readme](https://github.com/BrainCrumbz/caliburn-micro-wpf-notifyicon-poc/blob/master/README.md). Otherwise, feel free to ask.

HTH
Cheers
